"""
Rebuild Section 9 (Enhanced visualizations) of p5_strain_comparison.ipynb with
embedded outputs. Run AFTER run_p5_analysis.py has produced all CSVs/PNGs.

The cells carry both runnable code and pre-computed outputs (figures embedded as
base64 display_data, summary tables as stream text) so the notebook renders the
results without a 30-min FVA re-run, while remaining reproducible if executed.
"""
import json, base64
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT = Path(__file__).parent.parent
OUT_DIR = PROJECT / 'data' / 'intermediate'
NB_PATH = PROJECT / 'code' / 'p5_strain_comparison.ipynb'
CS_ORDER = ['Glucose', 'Glycerol', 'Maltose', 'Xylose']


# ── helpers ────────────────────────────────────────────────────────────────────
def _b64(fname):
    p = OUT_DIR / fname
    return base64.b64encode(p.read_bytes()).decode('utf-8') if p.exists() else None

def _stream(text_lines):
    return {'output_type': 'stream', 'name': 'stdout',
            'text': text_lines if isinstance(text_lines, list) else [text_lines]}

def _png(fname, desc='<Figure>'):
    b = _b64(fname)
    return {'output_type': 'display_data', 'metadata': {},
            'data': {'image/png': b, 'text/plain': [desc]}} if b else None

def _code(lines, outputs=None):
    src = lines if isinstance(lines, str) else '\n'.join(lines)
    return {'cell_type': 'code', 'execution_count': None,
            'metadata': {'section9': True}, 'source': src, 'outputs': outputs or []}

def _md(text):
    return {'cell_type': 'markdown', 'metadata': {'section9': True}, 'source': text}

def _read_csv(fname, **kw):
    p = OUT_DIR / fname
    try:
        return pd.read_csv(p, **kw)
    except Exception:
        return None


# ── build cells ────────────────────────────────────────────────────────────────
cells = []

cells.append(_md(
    '## 9. Enhanced visualizations\n\n'
    'Figures are generated by `run_p5_analysis.py` from the CSVs in '
    '`data/intermediate/`. Methodological choices addressing the reviewer: carbon '
    'sources fed at **equal C-mol** supply, non-growth ATP maintenance (**NGAM**) '
    'imposed, and flux variability analysis run **loopless** so reported ranges are '
    'thermodynamically attainable.'))

cells.append(_code(
    "import pandas as pd, numpy as np\n"
    "import matplotlib.pyplot as plt, seaborn as sns\n"
    "from IPython.display import Image, display\n"
    "sns.set_theme(style='whitegrid', context='notebook')\n"
    "OUT='../data/intermediate/'\n"
    "print('Loaded')",
    outputs=[_stream(['Loaded\n'])]))

# 9a EGC found & fixed
cells.append(_md(
    '### 9a. EGC screen — found and fixed (Q5)\n\n'
    'The eight strain models are EGC-free. The **Pan_oryzae** pan-model initially '
    'carried three EGCs (NADH, NADPH, L-Glutamate) from two thermodynamically '
    'inconsistent `OtherAsp_*` reaction pairs that only co-occur in the pan-model. '
    'Four reaction-bound changes (documented in `p3_simulations.ipynb`) eliminate '
    'all three; reverting those four bounds restores the EGCs, confirming causality. '
    'After curation, **all models × 12 carriers return zero dissipation flux.**'))
egc = _read_csv('strain_comparison_EGC.csv', index_col=0)
egc_txt = (f"EGC screen: max dissipation flux across {len(egc)} models x 12 carriers "
           f"= {egc.select_dtypes('number').max().max():.2e} mmol/gDW/h -> no EGCs\n"
           if egc is not None else "EGC CSV not found\n")
cells.append(_code(
    "egc = pd.read_csv(OUT+'strain_comparison_EGC.csv', index_col=0)\n"
    "print(f'Max dissipation flux ({len(egc)} models x 12 carriers): "
    "{egc.select_dtypes(\"number\").max().max():.2e} -> no EGCs')\n"
    "display(Image(OUT+'fig_EGC_beforeafter.png'))\n"
    "display(Image(OUT+'fig_EGC_heatmap.png'))",
    outputs=[o for o in [_stream([egc_txt]),
                         _png('fig_EGC_beforeafter.png', '<EGC before/after>'),
                         _png('fig_EGC_heatmap.png', '<EGC heatmap>')] if o]))

# 9b loopless rigor
cells.append(_md(
    '### 9b. Loopless flux variability (Q12 rigor)\n\n'
    'Standard FVA exploits internal thermodynamic loops and overstates flux ranges '
    '(e.g. adenylate kinase, nucleoside-diphosphate kinase span ±1000 mmol/gDW/h). '
    'Running FVA with `loopless=True` collapses loop-only ranges to their attainable '
    'values. All FVA results below use loopless ranges.'))
lc = _read_csv('strain_comparison_FVA_loopless_vs_standard.csv')
lc_txt = ''
if lc is not None:
    n = int((lc['loop_inflation'] > 1.0).sum())
    lc_txt = (f"Reaction-conditions with loop-inflated standard ranges (>1 unit): {n}\n"
              f"Top loop-inflated reactions are removed under loopless FVA.\n")
cells.append(_code(
    "lc = pd.read_csv(OUT+'strain_comparison_FVA_loopless_vs_standard.csv')\n"
    "print('Loop-inflated reaction-conditions (>1 unit):', int((lc.loop_inflation>1).sum()))\n"
    "display(Image(OUT+'fig_FVA_loopless_vs_standard.png'))",
    outputs=[o for o in [_stream([lc_txt]),
                         _png('fig_FVA_loopless_vs_standard.png', '<loopless vs standard>')] if o]))

# 9c carbon-normalized growth & yield
cells.append(_md(
    '### 9c. Carbon-normalised growth and yield (Q12, Q14)\n\n'
    'With equal C-mol supply, FBA growth and biomass yield per C-mol are near-identical '
    'across strains. Biomass yield per C-mol is uptake-rate independent and therefore '
    'comparable across substrates.'))
cells.append(_code(
    "display(Image(OUT+'fig_growth_yield.png'))",
    outputs=[o for o in [_png('fig_growth_yield.png', '<growth & yield>')] if o]))

# 9d phenotype concordance
cells.append(_md(
    '### 9d. Phenotype concordance: model vs BioLog (Q12)\n\n'
    'FBA reproduces most observed growth phenotypes. Discordances (blue boxes — model '
    'predicts growth where the wet lab shows none, e.g. **NRRL_5589** on glycerol/maltose) '
    'are explicit model-refinement targets, not hidden failures.'))
cells.append(_code(
    "display(Image(OUT+'fig_FBA_vs_biolog.png'))",
    outputs=[o for o in [_png('fig_FBA_vs_biolog.png', '<concordance>')] if o]))

# 9e pFBA cost
cells.append(_md(
    '### 9e. pFBA metabolic cost (Q14)\n\n'
    'Two defensible cost metrics: ATP turnover per biomass (energetic cost) and biomass '
    'yield per C-mol (carbon efficiency). Glycerol is the most energetically costly '
    'substrate per unit biomass; differences between strains are at the solver noise floor.'))
cells.append(_code(
    "display(Image(OUT+'fig_pFBA_efficiency.png'))",
    outputs=[o for o in [_png('fig_pFBA_efficiency.png', '<pFBA cost>')] if o]))

# 9f loopless FVA annotated
cells.append(_md(
    '### 9f. Loopless FVA flux ranges — top inter-strain variance (Q12, Q14)\n\n'
    'Reactions with the largest inter-strain variance in loopless flux range, per '
    'substrate. These are genuine accessory-gene-associated differences, not loop artifacts.'))
fva_imgs = [_png(f'fig_FVA_annotated_{cs}.png', f'<FVA {cs}>') for cs in CS_ORDER]
cells.append(_code(
    "for cs in ['Glucose','Glycerol','Maltose','Xylose']:\n"
    "    display(Image(OUT+f'fig_FVA_annotated_{cs}.png'))",
    outputs=[o for o in fva_imgs if o]))

# 9g accessory + single-deletion growth impact
cells.append(_md(
    '### 9g. Accessory reactions: flux activity and growth impact (Q13)\n\n'
    'Accessory reactions (present in 1–7 of 8 strains) with a non-zero **loopless** flux '
    'range on at least one substrate, grouped by subsystem, with their strain distribution. '
    'A direct single-deletion test shows **no accessory reaction individually affects the '
    'growth optimum** (max growth drop < 0.06% over 634 deletions).'))
acc = _read_csv('strain_comparison_accessory.csv')
acd = _read_csv('strain_comparison_accessory_deletion.csv')
acc_txt = ''
if acc is not None and not acc.empty:
    acc_txt += f"Flux-active accessory reactions (loopless): {acc['reaction'].nunique()}\n"
if acd is not None and not acd.empty:
    acc_txt += (f"Single deletions evaluated: {len(acd)}; "
                f"max growth drop {acd['pct_drop'].max():.3f}% (none essential)\n")
cells.append(_code(
    "acc = pd.read_csv(OUT+'strain_comparison_accessory.csv')\n"
    "acd = pd.read_csv(OUT+'strain_comparison_accessory_deletion.csv')\n"
    "print('Flux-active accessory reactions (loopless):', acc['reaction'].nunique())\n"
    "print('Max growth drop from a single accessory deletion: %.3f%%' % acd['pct_drop'].max())\n"
    "display(Image(OUT+'fig_accessory_subsystems.png'))\n"
    "display(Image(OUT+'fig_accessory_presence.png'))\n"
    "display(Image(OUT+'fig_accessory_deletion.png'))",
    outputs=[o for o in [_stream([acc_txt]),
                         _png('fig_accessory_subsystems.png', '<accessory subsystems>'),
                         _png('fig_accessory_presence.png', '<accessory presence>'),
                         _png('fig_accessory_deletion.png', '<accessory deletion>')] if o]))

# 9h NGAM
cells.append(_md(
    '### 9h. NGAM sensitivity (Q13)\n\n'
    'Growth decreases linearly with the non-growth ATP maintenance coefficient. The '
    'imposed value (1 mmol ATP/gDW/h) and the literature range for filamentous fungi '
    'are marked; growth conclusions are robust across this range. GAM = 49 mmol ATP/gDW '
    '(in biomass-formation reaction r1897).'))
cells.append(_code(
    "display(Image(OUT+'fig_NGAM_sensitivity.png'))",
    outputs=[o for o in [_png('fig_NGAM_sensitivity.png', '<NGAM>')] if o]))

# 9i subsystems
cells.append(_md(
    '### 9i. Subsystem activity profiles (Q14)\n\n'
    'pFBA flux aggregated by subsystem (fraction of total). Substrate-specific rewiring '
    'is consistent across strains.'))
sub_imgs = [_png(f'fig_subsystem_{cs}.png', f'<subsystem {cs}>') for cs in CS_ORDER]
cells.append(_code(
    "for cs in ['Glucose','Glycerol','Maltose','Xylose']:\n"
    "    display(Image(OUT+f'fig_subsystem_{cs}.png'))",
    outputs=[o for o in sub_imgs if o]))

# 9j summary
cells.append(_md('### 9j. Summary panel\n\n'
                 'Yield, BioLog phenotypes, ATP cost, and NGAM sensitivity in one figure.'))
cells.append(_code(
    "display(Image(OUT+'fig_summary_panel.png'))",
    outputs=[o for o in [_png('fig_summary_panel.png', '<summary>')] if o]))

# 9k alternative views (augment, do not replace, the figures above)
cells.append(_md(
    '### 9k. Alternative views of the same conclusions\n\n'
    'Complementary figures that convey the Q5/Q12–Q14 conclusions in different ways: the '
    '**standard-vs-loopless FVA scatter** (every reaction; loop artifacts collapse to ~0), '
    '**identical function / divergent content** (growth identical, accessory complement '
    '29–149 per strain), the **model–BioLog confusion matrix** (100% sensitivity, 0/2 '
    'specificity), and **substrate-specific subsystem rewiring** (Δ vs glucose). The four are '
    'combined into a single multi-panel manuscript figure (`fig_mechanistic_4panel`).'))
_alt = [('fig_FVA_loopless_scatter.png', '<std vs loopless scatter>'),
        ('fig_function_vs_content.png', '<function vs content>'),
        ('fig_concordance_matrix.png', '<concordance matrix>'),
        ('fig_subsystem_delta.png', '<subsystem delta>'),
        ('fig_mechanistic_4panel.png', '<manuscript 4-panel>')]
cells.append(_code(
    "for f in ['fig_FVA_loopless_scatter','fig_function_vs_content','fig_concordance_matrix',\n"
    "          'fig_subsystem_delta','fig_mechanistic_4panel']:\n"
    "    display(Image(OUT+f+'.png'))",
    outputs=[o for o in [_png(f, d) for f, d in _alt] if o]))

# 9l revised manuscript figure (variation confined to dispensable accessory metabolism)
cells.append(_md(
    '### 9l. Proposed manuscript figure\n\n'
    'A three-panel figure for the manuscript (`fig_mechanistic_manuscript`) showing that '
    'intra-species variation is confined to dispensable accessory metabolism and that '
    'substrate-driven rewiring is consistent across strains: **(A)** the reactions varying most '
    'between strains (inter-strain variance of loopless FVA range) — fatty-acid biosynthesis and '
    'accessory oxidoreductases; **(B)** single-reaction deletion — 169 essential core reactions '
    'vs 0/634 accessory deletions affecting growth; **(C)** substrate-specific subsystem rewiring '
    'with the 8 strains overlapping tightly (max inter-strain SD ≈ 3 percentage points).'))
_man = [('fig_mechanistic_manuscript.png', '<manuscript figure (3-panel)>'),
        ('fig_strain_variable_reactions.png', '<A reactions varying most>'),
        ('fig_leave_one_out.png', '<B leave-one-out>'),
        ('fig_subsystem_consistency.png', '<C rewiring consistency>')]
cells.append(_code(
    "for f in ['fig_mechanistic_manuscript','fig_strain_variable_reactions',\n"
    "          'fig_leave_one_out','fig_subsystem_consistency']:\n"
    "    display(Image(OUT+f+'.png'))",
    outputs=[o for o in [_png(f, d) for f, d in _man] if o]))


# ── write notebook ─────────────────────────────────────────────────────────────
nb = json.loads(NB_PATH.read_text(encoding='utf-8'))

def _is_sec9(cell):
    if cell.get('metadata', {}).get('section9'):       # cells we created (idempotent)
        return True
    src = ''.join(cell.get('source', ''))
    # legacy heuristics (cells from earlier versions without the metadata tag)
    if cell.get('cell_type') == 'code' and ('OUT+' in src or 'OUT +' in src or 'Image(OUT' in src):
        return True   # Section 9 code cells use the bare `OUT` var; sections 0-8 use OUT_DIR
    return ('## 9.' in src or '### 9' in src or 'fig_EGC' in src or
            'fig_summary_panel' in src or 'fig_FVA_loopless' in src or
            'fig_growth_yield' in src or
            src.strip().startswith("import pandas as pd, numpy"))

existing = [i for i, c in enumerate(nb['cells']) if _is_sec9(c)]
for i in sorted(existing, reverse=True):
    nb['cells'].pop(i)
if existing:
    print(f"Removed {len(existing)} pre-existing Section 9 cells")

nb['cells'].extend(cells)
NB_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print(f"Wrote {len(cells)} Section 9 cells to {NB_PATH.name}")
n_png = sum(1 for c in cells for o in c.get('outputs', [])
            if o.get('output_type') == 'display_data')
print(f"Embedded {n_png} figures")
